### ISSUE TITLE
Feature request: Brotli compressed svgs

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-image-service#188]
They're quite tiny anyway, so not sure if there's much to be gained, but it's possible to get fastly to allow the server to compress as it likes https://community.fastly.com/t/brotli-compression-support/578.

This goes for build service and polyfill too (where the gains would be greater), and I'm planning on supporting it for next's built assets by pushing precompressed files up to s3

**Comment by JakeChampion** [comment]
We can't use Fastly's brotli compression because it is only available via their H2O server, which is not used when using a legacy certificate (which www.ft.com is using).

We can't use brotli at the application level as the image service streams responses, and I don't know of a way to do streaming brotli compression.

When Fastly move to using their H2O server for all HTTP versions, we can turn on brotli compression via Fastly.

**Comment by wheresrhys** [comment]
fair dos
