### ISSUE TITLE
Feature request: Support Content API URLs

### ISSUE THREAD

**Issue by davidlintonattheft** [Financial-Times/origami-image-service#189]
Currently Origami supports IDs of the form

`ftcms:59cbff70-41a6-11e5-b98b-87c7270955cf`

These check in http://prod-upp-image-read.ft.com/ and  http://im.ft-static.com/content/images/ for the image, which is fine for images for Methode but doesn't work for blogs (including FastFT)

I'd like the imageservice to support URLs of the form
http://api.ft.com/content/59cbff70-41a6-11e5-b98b-87c7270955cf

This resource is a JSON structure including the actual binary URL of the image.
This would work for all content in the platform.

**Comment by JakeChampion** [comment]
@davidlintonattheft How can I get an API key to view - http://api.ft.com/content/59cbff70-41a6-11e5-b98b-87c7270955cf ?

**Comment by davidlintonattheft** [comment]
API gateway team have a [key request form](https://docs.google.com/a/ft.com/forms/d/1qSPqTl1YdbWPNGEjC3ZmJlmwARf1ygGFlgY0C3UMZB4/viewform)

**Comment by davidlintonattheft** [comment]
In case I wasn't clear, the enhancement meant using that as a backend for the `ftcms:` scheme so it works more reliably, though it would also be convenient to be able to supply a Content API URL directly to the image service.

**Comment by JakeChampion** [comment]
@davidlintonattheft Would supporting the Content API URLs simplify our FTCMS checks? I.E. Could we stop looking in http://prod-upp-image-read.ft.com/ and http://im.ft-static.com/content/images/ and only look in the Content API?

**Comment by davidlintonattheft** [comment]
I guess so---it would also give us confidence that these IDs actually refer to real things in the platform as we're supposed to be the ones managing them.

**Comment by lucas42** [comment]
At the moment, http://im.ft-static.com/content/images/ may be needed by the occasional client using CAPI v1 to get smaller images.  This is because v1 minted unique IDs for different sizes of image.  
In v2, we only have an ID for the master image as we expect images to be scaled down by the front-end or image service.
Clients are due to move away from CAPI v1 by the end of June, at which point the API call David suggests will work for all images we support in the platform.

**Comment by JakeChampion** [comment]
PR for this #406

**Comment by JakeChampion** [comment]
Added via #406
